# Theme settings
doks:
    baseurl: ""
    color_theme: white # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Griffin D. Chure | PhD Thesis
            image:
    footer:
        content:
            logo:
                text: Griffin D. Chure | PhD Thesis
                image:
            copyright: Copyright &copy; 2020. - Griffin D. Chure <br>All rights reserved.
        social_list:
            - network_name: twitter
              profile_url: 'http://twitter.com/gdchure'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'data/', 'phd/', 'phd.egg-info/', 'sandbox', 'true']
permalink: /:title/
gems:
  - jekyll-numbered-headings
  - jekyll-pandoc-multiple-formats

markdown: Pandoc
pandoc:
    skip:
      full: false
      posts: false
      categories: false 
    flags: >
     --filter pandoc-xnos 
     --filter pandoc-citeproc
     --filter pandoc-shortcaption
     --default-image-extension=svg
     --resource-path=src/chapter_01/figs:src/chapter_02/figs:
     --top-level-division chapter 
     --mathjax